### ISSUE TITLE
OpenAPI 3.1.0 support: analysis of build fragments

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-js#2837]
First part of this issue is to analyze npm dist fragment and determine what can we do by limiting it's size.

Second part of this issue is to perform analysis on swagger-client UMD bundle, and possibly decrease the bundle size as much as possible.

**TODO**:

- [x] https://github.com/swagger-api/apidom/issues/2562
- [x] https://github.com/swagger-api/apidom/pull/2567
- [x] decrease size of npm package
- [x] decrease size of UMD bundle

**Comment by char0n** [comment]
npm package size before the optimization: 

```
npm notice package size:  4.5 MB                                  
npm notice unpacked size: 26.9 MB     
```

**Comment by char0n** [comment]
UMD bundle size **before** the OpenAPI 3.1.0 implementation

```
228K
```

UMD bundle size **after** the OpenAPI 3.1.0 implementation

```
436K
```

UMD bundle size **after** the OpenAPI 3.1.0 implementation

```
329K
```
